# Generated by Django 5.0.3 on 2024-03-08 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cover_image",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="wagtailimages.image"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="django_images"),
        ),
    ]
